name: generate-localized-scripts

on:
  push:
    paths:
      - "**/utilkit.src.*"
  workflow_dispatch:

jobs:
  generate-localized-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for accurate file change detection
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: "**/utilkit.src.*"

      - name: Run Localization Engine for Changed Files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Processing changed source files..."
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "--- Running engine for $file ---"
            python scripts/localization_engine.py "$file"
          done

      - name: Upload localized scripts
        uses: actions/upload-artifact@v4
        with:
          name: localized-scripts
          path: "**/localized/"
          if-no-files-found: warn

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          # Commit message now reflects the rule-driven nature of the process
          git commit -m "chore: Auto-generate and translate localized scripts based on rules" || echo "No changes to commit"
          git push
