name: generate-localized-scripts

on:
  push:
    paths:
      - "**/utilkit.src.*"
  workflow_dispatch:

jobs:
  generate-localized-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for accurate file change detection on push
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Get changed files on push
        id: changed-files
        if: github.event_name == 'push'
        uses: tj-actions/changed-files@v46
        with:
          files: "**/utilkit.src.*"

      - name: Run Engine for Changed Files (on push)
        if: github.event_name == 'push' && steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Processing changed source files from push..."
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "--- Running engine for $file ---"
            python scripts/localization_engine.py "$file"
          done

      - name: Run Engine for All Files (on workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Processing all source files on manual trigger..."
          find . -type f -name "utilkit.src.*" | while read file; do
            echo "--- Running engine for $file ---"
            python scripts/localization_engine.py "$file"
          done

      - name: Upload localized scripts
        uses: actions/upload-artifact@v4
        with:
          name: localized-scripts
          path: "**/localized/"
          if-no-files-found: warn

      - name: Commit and push changes
        run: |
          # Check if there are any changes to commit
          if [[ -n $(git status -s) ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "chore: Auto-generate and translate localized scripts" || echo "No changes to commit"
            git push
          else
            echo "No changes to commit."
          fi
