name: generate-localized-scripts

on:
  push:
    paths:
      - "sh/utilkit.sh"
  workflow_dispatch:

jobs:
  generate-localized-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for accurate file change detection on push
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install GlocalText from source
        run: |
          python -m pip install --upgrade pip
          # Install dependencies, assuming they are in requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Install the glocaltext package in editable mode from local source
          pip install -e .

      - name: Get changed source files
        id: changed-files
        if: github.event_name == 'push'
        uses: tj-actions/changed-files@v46
        with:
          files: "sh/utilkit.sh"

      - name: Run GlocalText Localization
        run: glocaltext run sh

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A

          # Check if there are any changes to commit
          if ! git diff-index --quiet HEAD; then
            COMMIT_MSG_TITLE="chore: Auto-generate and translate localized scripts"
            COMMIT_MSG_BODY=""

            if [[ "${{ github.event_name }}" == "push" && "${{ steps.changed-files.outputs.any_changed }}" == "true" ]]; then
              COMMIT_MSG_BODY="Triggered by changes in the following source file(s):\n"
              # Get commit info for each changed file
              for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                COMMIT_HASH=$(git log -1 --pretty=format:%h -- "$file")
                COMMIT_DATE=$(git log -1 --pretty=format:%cI -- "$file")
                COMMIT_MSG_BODY="${COMMIT_MSG_BODY}\n- ${COMMIT_HASH} | ${COMMIT_DATE} | ${file}"
              done
            fi
            
            # Commit with a multi-line message
            git commit -m "$COMMIT_MSG_TITLE" -m "$COMMIT_MSG_BODY"
            git push
          else
            echo "No changes to commit."
          fi
