name: Generate Localized Scripts

on:
  push:
    paths:
      - "utilkit.sh"
      - "utilkit.json"
  workflow_dispatch:

jobs:
  generate-localized-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Extract version
        id: version
        run: |
          VERSION=$(grep -oP 'Version="\K[^"]+' utilkit.sh || echo "unknown")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate localized versions
        run: |
          mkdir -p localized
          languages=$(jq -r 'keys[]' utilkit.json)
          for lang in $languages; do
            echo "Generating $lang version..."
            sed_script=$(mktemp)
            jq -r ".[\"$lang\"] | to_entries[] | .key" utilkit.json | while read -r key; do
              value=$(jq -r ".[\"$lang\"][\"$key\"]" utilkit.json)
              escaped_value=$(echo "$value" | sed -e 's/[\/&]/\\&/g' -e 's/\[/\\[/g' -e 's/\]/\\]/g')
              echo "s/\\*#${key}#\\*/${escaped_value}/g" >> "$sed_script"
            done
            cp utilkit.sh "localized/utilkit_${lang}.sh"
            sed -i -f "$sed_script" "localized/utilkit_${lang}.sh"
            rm "$sed_script"
          done

      - name: Upload localized scripts
        uses: actions/upload-artifact@v4
        with:
          name: localized-scripts
          path: localized/

      - name: Commit and push localized scripts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mkdir -p localized
          git add localized/
          git commit -m "Update localized utilkit.sh ${{ steps.version.outputs.version }}" || echo "No changes to commit"
          git push
